<?php
$this->renderPartial(
    '/layouts/block_items',
    array(
        'back'=>$this->createUrl('js/index'),
        'title'=>'jquery_plugin',
        'items'=>array(
            'js_jquery_plugin_01',
            'js_jquery_plugin_02',
        )
    )
);
?>